version: '3.6'
services:
  ms_api1:
    image: microservice.apiservice
    build: 
        context: /root/MicroServiceTemp/Service/ApiServiceBase
    ports:
      - 5001:8080/tcp
    volumes: 
        - /root/MicroServiceTemp/configs/ServerConfig/appsettings_5001.json:/root/MicroServiceTemp/Service/ApiServiceBase/appsetting.json
      
  ms_api2:
    image: microservice.apiservice
    ports:
      - 5002:8080/tcp
    volumes: 
        - /root/MicroServiceTemp/configs/ServerConfig/appsettings_5002.json:/app/appsetting.json

  ms_api3:
    image: microservice.apiservice
    ports:
      - 5003:8080/tcp
    volumes: 
        - /root/MicroServiceTemp/configs/ServerConfig/appsettings_5003.json:/app/appsetting.json

  nginx:
    image: nginx:latest
    ports: 
        - 9001:8080/tcp
    volumes: 
        - /root/MicroServiceTemp/logs/nginx/:/var/log/nginx/
        - /root/MicroServiceTemp/configs/nginx.conf:/etc/nginx/nginx.conf

networks:
  frontend:
  backend:

volumes:
  db-data: