version: '3.3'
services:
  ms_api1:
    image: microservice.apiservice
    build: 
        context: /root/MicroServiceTemp/Service/ApiServiceBase
    ports:
      - 5001:8080
      
  ms_api2:
    image: microservice.apiservice
    ports:
      - 5002:8080

  ms_api3:
    image: microservice.apiservice
    ports:
      - 5003:8080

networks:
  frontend:
  backend:

volumes:
  db-data: