version: '3.6'
services:
  ms_api1:
    image: apiservice
    build: 
        context: /root/MicroServiceTemp/Service/Release
    ports:
      - 5001:80/tcp
    volumes: 
        - /root/MicroServiceTemp/configs/ServerConfig/appsettings_5001.json:/app/appsettings.json
      
  ms_api2:
    image: apiservice
    ports:
      - 5002:80/tcp
    volumes: 
        - /root/MicroServiceTemp/configs/ServerConfig/appsettings_5002.json:/app/appsettings.json

  ms_api3:
    image: apiservice
    ports:
      - 5003:80/tcp
    volumes: 
        - /root/MicroServiceTemp/configs/ServerConfig/appsettings_5003.json:/app/appsettings.json

networks:
  frontend:
  backend:

volumes:
  db-data: